services:
  frontEnd:
    image: sasfront:1.00
    build:
      context: .
      dockerfile: frontDockerfile

    ports:
      - "80:80"

  backEnd:
   image: sasback:1.00
   build:
      context: .
      dockerfile: backDockerfile
   ports:
      - "8080:8080"